/// Google Places API (New) — Table A types valid for `includedType` filter.
/// https://developers.google.com/maps/documentation/places/web-service/place-types
pub static PLACE_TYPES: &[&str] = &[
    "acai_shop",
    "afghani_restaurant",
    "african_restaurant",
    "american_restaurant",
    "argentinian_restaurant",
    "asian_fusion_restaurant",
    "asian_restaurant",
    "australian_restaurant",
    "austrian_restaurant",
    "bagel_shop",
    "bakery",
    "bangladeshi_restaurant",
    "bar",
    "bar_and_grill",
    "barbecue_restaurant",
    "basque_restaurant",
    "bavarian_restaurant",
    "beer_garden",
    "belgian_restaurant",
    "bistro",
    "brazilian_restaurant",
    "breakfast_restaurant",
    "brewery",
    "brewpub",
    "british_restaurant",
    "brunch_restaurant",
    "buffet_restaurant",
    "burmese_restaurant",
    "burrito_restaurant",
    "cafe",
    "cafeteria",
    "cajun_restaurant",
    "cake_shop",
    "californian_restaurant",
    "cambodian_restaurant",
    "candy_store",
    "cantonese_restaurant",
    "car_dealer",
    "car_rental",
    "car_repair",
    "car_wash",
    "caribbean_restaurant",
    "cat_cafe",
    "chicken_restaurant",
    "chicken_wings_restaurant",
    "chilean_restaurant",
    "chinese_noodle_restaurant",
    "chinese_restaurant",
    "chocolate_factory",
    "chocolate_shop",
    "cocktail_bar",
    "coffee_roastery",
    "coffee_shop",
    "coffee_stand",
    "colombian_restaurant",
    "confectionery",
    "croatian_restaurant",
    "cuban_restaurant",
    "czech_restaurant",
    "danish_restaurant",
    "deli",
    "dessert_restaurant",
    "dessert_shop",
    "dim_sum_restaurant",
    "diner",
    "dog_cafe",
    "dog_park",
    "donut_shop",
    "dumpling_restaurant",
    "dutch_restaurant",
    "eastern_european_restaurant",
    "ethiopian_restaurant",
    "european_restaurant",
    "falafel_restaurant",
    "family_restaurant",
    "farmers_market",
    "fast_food_restaurant",
    "filipino_restaurant",
    "fine_dining_restaurant",
    "fish_and_chips_restaurant",
    "fitness_center",
    "flea_market",
    "fondue_restaurant",
    "food_court",
    "french_restaurant",
    "fusion_restaurant",
    "gas_station",
    "gastropub",
    "german_restaurant",
    "gift_shop",
    "golf_course",
    "greek_restaurant",
    "grocery_store",
    "gym",
    "gyro_restaurant",
    "halal_restaurant",
    "hamburger_restaurant",
    "hardware_store",
    "hawaiian_restaurant",
    "health_food_store",
    "hindu_temple",
    "historical_landmark",
    "home_goods_store",
    "home_improvement_store",
    "hookah_bar",
    "hot_dog_restaurant",
    "hot_pot_restaurant",
    "hungarian_restaurant",
    "ice_cream_shop",
    "ice_skating_rink",
    "indian_restaurant",
    "indonesian_restaurant",
    "irish_pub",
    "irish_restaurant",
    "israeli_restaurant",
    "italian_restaurant",
    "japanese_curry_restaurant",
    "japanese_izakaya_restaurant",
    "japanese_restaurant",
    "jewelry_store",
    "juice_shop",
    "kebab_shop",
    "korean_barbecue_restaurant",
    "korean_restaurant",
    "latin_american_restaurant",
    "lawyer",
    "laundry",
    "lebanese_restaurant",
    "library",
    "liquor_store",
    "lounge_bar",
    "malaysian_restaurant",
    "market",
    "massage",
    "meal_delivery",
    "meal_takeaway",
    "mediterranean_restaurant",
    "mexican_restaurant",
    "middle_eastern_restaurant",
    "mongolian_barbecue_restaurant",
    "moroccan_restaurant",
    "movie_theater",
    "noodle_shop",
    "north_indian_restaurant",
    "oyster_bar_restaurant",
    "pakistani_restaurant",
    "pastry_shop",
    "persian_restaurant",
    "peruvian_restaurant",
    "pharmacy",
    "pizza_delivery",
    "pizza_restaurant",
    "polish_restaurant",
    "portuguese_restaurant",
    "post_office",
    "pub",
    "ramen_restaurant",
    "restaurant",
    "romanian_restaurant",
    "russian_restaurant",
    "salad_shop",
    "sandwich_shop",
    "scandinavian_restaurant",
    "seafood_restaurant",
    "shawarma_restaurant",
    "shoe_store",
    "shopping_mall",
    "snack_bar",
    "soul_food_restaurant",
    "soup_restaurant",
    "south_american_restaurant",
    "south_indian_restaurant",
    "southwestern_us_restaurant",
    "spanish_restaurant",
    "sports_bar",
    "sri_lankan_restaurant",
    "steak_house",
    "sushi_restaurant",
    "swiss_restaurant",
    "swimming_pool",
    "taco_restaurant",
    "taiwanese_restaurant",
    "tapas_restaurant",
    "tea_house",
    "tea_store",
    "tex_mex_restaurant",
    "thai_restaurant",
    "thrift_store",
    "tibetan_restaurant",
    "tonkatsu_restaurant",
    "turkish_restaurant",
    "ukrainian_restaurant",
    "vegan_restaurant",
    "vegetarian_restaurant",
    "vietnamese_restaurant",
    "wine_bar",
    "winery",
    "yakiniku_restaurant",
    "yakitori_restaurant",
    "zoo",
];

/// Fuzzy-match place types: returns types containing any of the space-separated
/// query words as substrings, scored by how early/many matches occur.
pub fn filter_types(query: &str, max: usize) -> Vec<&'static str> {
    if query.is_empty() {
        return Vec::new();
    }

    let query_lower = query.to_lowercase();
    let terms: Vec<&str> = query_lower.split_whitespace().collect();
    if terms.is_empty() {
        return Vec::new();
    }

    let mut scored: Vec<(usize, &'static str)> = PLACE_TYPES
        .iter()
        .filter_map(|&t| {
            // All terms must match somewhere in the type string
            let all_match = terms.iter().all(|term| t.contains(term));
            if !all_match {
                return None;
            }
            // Score: prefer prefix matches, then shorter strings
            let score = if t.starts_with(terms[0]) {
                0 // best: prefix match on first term
            } else {
                1
            };
            Some((score * 1000 + t.len(), t))
        })
        .collect();

    scored.sort_by_key(|(score, _)| *score);
    scored.into_iter().take(max).map(|(_, t)| t).collect()
}
